version: '2'
networks:
  api:
  db:
services:
  db:
    image: mysql:8.0.11
    volumes:
      - ./volumes/db:/var/lib/mysql
    networks:
      - db
    ports:
     - "3306:3306"
  api:
    image: node:10.5.0
    ports:
    - "3000:3000"
    volumes:
      - ./api:/api
    command: sh -c "cd /api && npm install && npm run nodemon"
    networks:
      - db
      - api
    depends_on:
      - db
#docker-compose -p docker up --build
