type User {
  _id: ID
  name: String!
  lastname: String!
  username: String!
  email: String!
  password: String!
  avatar: String
  createdAt: String
  updatedAt: String
}

type Post {
  _id: ID
  title: String!
  slug: String!
  summary: String
  content: String
  imageUrl: String
  categories: [String]!
  published: Boolean!
  likes: Int
  author: User!
  createdAt: String
  updatedAt: String
}

type Query {
  getPosts: [Post]
  getPost(slug: String!): Post
}

type Mutation {
  createPost(title: String!, summary: String, content: String, imageUrl: String, categories: [String]!, published: Boolean, author: ID!): Post!
}